FROM node:alpine
WORKDIR '/app'
COPY ./package.json .
RUN npm install
RUN npm install -g nodemon
COPY . .
ENTRYPOINT npx nodemon -L -e ts,json --exec 'node --inspect=0.0.0.0 -r ts-node/register index.ts'
